### ISSUE TITLE
ghost people going into Xv_m and Xv_h

### ISSUE THREAD

**Issue by yangclaraliu** [jarawees/covidmodel-hitap#1]
@seabbs
https://github.com/jarawees/covidmodel-hitap/blob/a274318719189c3057d42efe8080053cd8a6d9ea/code/covidm_for_fitting/model_v2/sim_compartment.cpp#L278-L285

**Comment by yangclaraliu** [comment]
temporary fix provided by using tiny doses provided on the first day of vaccine distribution

**Comment by yangclaraliu** [comment]
![image](https://user-images.githubusercontent.com/11761561/201875209-36c2067d-2585-4ad7-a9c7-06fd21347ed0.png)
There are people flowing into Sv_h and Rv_h when there are not intended to

**Comment by seabbs** [comment]
This is looking increasingly like numerical instability isn't it....
