### ISSUE TITLE
2023-05-26 email issue 1

### ISSUE THREAD

**Issue by yangclaraliu** [jarawees/covidmodel-hitap#20]
https://github.com/jarawees/covidmodel-hitap/blob/3d00d4b334ed393fd478bb7d85943bb82133699a/code/0_4_2_Primary.R#LL7C1-L7C106

sapply(1:nrow(owid_vac), function(x) sum(owid_vac$fully_vaccinated_adult_daily[1:x])) -> daily_all_adults

0_4_2_Primary.R
Line 7: change y to x (this function is throwing up an error)

I am not sure where you found `y`?

**Comment by SiobhanSiobhan** [comment]
No idea, you are right that GitHub seems to be fine but two of us checked and had this after pulling the most recent version! OK, not an issue seeing as it is fine on GitHub for the same branch that we are using. Thank you for checking :)
