### ISSUE TITLE
Efficacy weights used in update_u_y function

### ISSUE THREAD

**Issue by jarawees** [jarawees/covidmodel-hitap#23]
@yangclaraliu, we aren't sure why efficacy_weights_test (dummy efficacy weights) is used in update_u_y function (line 262 below)? Isn't it supposed to be a result of different vaccine composition? Please correct me if I'm wrong.

https://github.com/jarawees/covidmodel-hitap/blob/41d6d73c5101fcda77c6ae1a2aafca2b04ff348c/code/0_1_util_functions.R#L247-L263

**Comment by yangclaraliu** [comment]
Thank you for the question @jarawees 
`efficacy_weights` is now a parameter that's been retired. 
If you scroll down to `parameterise_setting`, which is function that wraps everything together, you can see that in `update_u_y` what's being used is `efficacy_weights_one`. This `efficacy_weights_one` set is essentially all 1s - this is how we "retired" the parameter without having to structurally change the functions. Changes in the proportion vaccinated flowing into different protection levels is now implemented using `scenario3_primary` and `scenario3_booster`.
