### ISSUE TITLE
double check definition of Khoury et al. health end points' definitions

### ISSUE THREAD

**Issue by yangclaraliu** [jarawees/covidmodel-hitap#5]
How many are there?
How are they defined?
- mild and severe
There are currently five stages in the model ranging from infection to mortality

**Comment by PritaKing** [comment]
Note data from Supplementary Table S3

Severe Covid-19 was defined as one of the following criteria: 
- respiratory rate of 30 or more breaths per minute;
- heart rate at or exceeding 125 beats per minute;
- oxygen saturation at 93% or less while the participant was breathing ambient air at sea level or a ratio of the partial pressure of oxygen to the fraction of inspired oxygen below 300 mm Hg respiratory failure; 
- acute respiratory distress syndrome; 
- evidence of shock (systolic blood pressure <90 mm Hg, diastolic blood pressure <60 mm Hg, or a need for vasopressors);
- clinically significant acute renal, hepatic, or neurologic dysfunction;
- admission to an intensive care unit; and 
**- death**
